Repository LuciferEOS/Goob-Station1, pull requests merged in 2025-04, with the labels that each got.

#3 я принимаю тяжёлые наркотики
  Content.Goobstation.Client/NTR/UI/NTRTaskHistoryEntry.xaml.cs
  Content.Goobstation.Client/NTR/UI/TaskEntry.xaml.cs
  Content.Goobstation.Server/NTR/Documents/RandomDocumentSystem.cs
  Content.Goobstation.Server/NTR/NTRTaskSystem.cs
  Content.Goobstation.Shared/NTR/NtrTaskPrototype.cs
  Content.Goobstation.Shared/NTR/NtrTaskProviderComponent.cs
  Content.Goobstation.Shared/NTR/RandomDocumentComponent.cs
  Content.Goobstation.Shared/NTR/SharedNtrTaskSystem.cs
  Content.Goobstation.Shared/NTR/TaskCompletedEvent.cs
  Resources/Locale/en-US/_Goobstation/NTR/ntr.ftl
  Resources/Prototypes/_Goobstation/Catalog/Bounties/ntr_bounties.yml
  Resources/Prototypes/_Goobstation/NTR/docs.yml
Labels: S: Untriaged, size/M, Changes: UI

#4 добавление очков + неожиданный апстримчик
  Content.Goobstation.Client/NTR/UI/NtrTaskHistoryEntry.xaml.cs
  Content.Goobstation.Client/NTR/UI/NtrTaskMenu.xaml.cs
  Content.Goobstation.Server/NTR/NTRTaskSystem.cs
  Content.Goobstation.Shared/NTR/Events/TaskCompletedEvent.cs
  Content.Goobstation.Shared/NTR/NtrAccountClientComponent.cs
  Content.Goobstation.Shared/NTR/SharedNtrTaskSystem.cs
  Content.Goobstation.Shared/NTR/StationNtrAccountComponent.cs
  Content.Server/Store/Systems/StoreSystem.cs
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/Entities/Stations/nanotrasen.yml
  Resources/Prototypes/_Goobstation/NTR/Store/executive_briefcase.yml
Labels: S: Untriaged, size/M, Changes: Sprites, Changes: UI

#6 Fix revert
  Content.Goobstation.Client/NTR/UI/NtrTaskHistoryEntry.xaml.cs
  Content.Goobstation.Client/NTR/UI/NtrTaskMenu.xaml.cs
  Content.Goobstation.Server/NTR/NTRTaskSystem.cs
  Content.Goobstation.Server/NTR/Scan/BriefcaseScannerSystem.cs
  Content.Goobstation.Shared/NTR/Events/TaskCompletedEvent.cs
  Content.Goobstation.Shared/NTR/NtrAccountClientComponent.cs
  Content.Goobstation.Shared/NTR/SharedNtrTaskSystem.cs
  Content.Goobstation.Shared/NTR/StationNtrAccountComponent.cs
  Content.Server/Store/Systems/StoreSystem.cs
  Resources/Locale/en-US/_Goobstation/NTR/ntr.ftl
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/Entities/Stations/nanotrasen.yml
  Resources/Prototypes/_Goobstation/Entities/Effects/bluespace_teleportation.yml
  Resources/Prototypes/_Goobstation/NTR/Store/executive_briefcase.yml
Labels: S: Untriaged, size/M, Changes: UI

#9 Feature/ntr task fixes
  Content.Goobstation.Server/NTR/NTRTaskSystem.cs
  Content.Goobstation.Shared/NTR/Events/TaskCompletedEvent.cs
  Content.Goobstation.Shared/NTR/NtrTaskPrototype.cs
  Content.Goobstation.Shared/NTR/SharedNtrTaskSystem.cs
  Resources/Prototypes/_Goobstation/Catalog/Bounties/ntr_bounties.yml
Labels: S: Untriaged, size/S

#10 localization
  Content.Goobstation.Client/NTR/UI/NtrTaskBoundUserInterface.cs
  Content.Goobstation.Client/NTR/UI/NtrTaskHistoryEntry.xaml.cs
  Content.Goobstation.Client/NTR/UI/NtrTaskMenu.xaml
  Content.Goobstation.Client/NTR/UI/TaskEntry.xaml
  Content.Goobstation.Client/NTR/UI/TaskEntry.xaml.cs
  Content.Goobstation.Common/NTR/NtrAccountBalanceUpdatedEvent.cs
  Content.Goobstation.Server/NTR/NTRTaskSystem.cs
  Content.Goobstation.Shared/NTR/Events/NtrListingPurchaseEvent.cs
  Content.Goobstation.Shared/NTR/NtrAccountClientComponent.cs
  Content.Goobstation.Shared/NTR/NtrBankAccountComponent.cs
  Content.Goobstation.Shared/NTR/NtrClientAccountComponent.cs
  Content.Goobstation.Shared/NTR/NtrTaskConsoleComponent.cs
  Content.Goobstation.Shared/NTR/NtrTaskPrototype.cs
  Content.Goobstation.Shared/NTR/SharedNtrTaskSystem.cs
  Content.Server/Store/Systems/StoreSystem.Ui.cs
  Resources/Locale/en-US/_Goobstation/NTR/ntr.ftl
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/_Goobstation/Catalog/Bounties/ntr_tasks.yml
  Resources/Prototypes/_Goobstation/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/_Goobstation/NTR/Store/executive_briefcase.yml
Labels: size/M, Changes: UI

#8 i want to kill myself
  Content.Goobstation.Client/NTR/UI/NtrTaskBoundUserInterface.cs
  Content.Goobstation.Client/NTR/UI/NtrTaskHistoryEntry.xaml.cs
  Content.Goobstation.Client/NTR/UI/NtrTaskMenu.xaml
  Content.Goobstation.Client/NTR/UI/TaskEntry.xaml
  Content.Goobstation.Client/NTR/UI/TaskEntry.xaml.cs
  Content.Goobstation.Common/NTR/NtrAccountBalanceUpdatedEvent.cs
  Content.Goobstation.Server/NTR/Documents/RandomDocumentSystem.cs
  Content.Goobstation.Server/NTR/Documents/SpamDocumentSystem.cs
  Content.Goobstation.Server/NTR/NTRTaskSystem.cs
  Content.Goobstation.Server/NTR/Scan/BriefcaseScannerSystem.cs
  Content.Goobstation.Shared/NTR/Documents/RandomDocumentComponent.cs
  Content.Goobstation.Shared/NTR/Documents/SpamDocumentComponent.cs
  Content.Goobstation.Shared/NTR/Events/NtrListingPurchaseEvent.cs
  Content.Goobstation.Shared/NTR/Events/TaskCompletedEvent.cs
  Content.Goobstation.Shared/NTR/Events/TaskFailedEvent.cs
  Content.Goobstation.Shared/NTR/NtrAccountClientComponent.cs
  Content.Goobstation.Shared/NTR/NtrBankAccountComponent.cs
  Content.Goobstation.Shared/NTR/NtrClientAccountComponent.cs
  Content.Goobstation.Shared/NTR/NtrTaskConsoleComponent.cs
  Content.Goobstation.Shared/NTR/NtrTaskData.cs
  Content.Goobstation.Shared/NTR/NtrTaskDatabaseComponent.cs
  Content.Goobstation.Shared/NTR/NtrTaskHistoryData.cs
  Content.Goobstation.Shared/NTR/NtrTaskPrototype.cs
  Content.Goobstation.Shared/NTR/SharedNtrTaskSystem.cs
  Content.Server/Store/Systems/StoreSystem.Ui.cs
  Resources/Audio/_Goobstation/DropPod/attributions.yml
  Resources/Audio/_Goobstation/DropPod/closet_open.ogg
  Resources/Audio/_Goobstation/DropPod/podwoosh.ogg
  Resources/Audio/_Goobstation/DropPod/supplypodlandig.ogg
  Resources/Locale/en-US/_Goobstation/NTR/ntr.ftl
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/_Goobstation/Catalog/Bounties/ntr_bounties.yml
  Resources/Prototypes/_Goobstation/Catalog/Bounties/ntr_tasks.yml
  Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/_Goobstation/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/_Goobstation/NTR/Catalog/ntr_catalog.yml
  Resources/Prototypes/_Goobstation/NTR/Catalog/pods.yml
  Resources/Prototypes/_Goobstation/NTR/Crates/products.yml
  Resources/Prototypes/_Goobstation/NTR/Events/eventstarter.yml
  Resources/Prototypes/_Goobstation/NTR/Store/executive_briefcase.yml
  Resources/Prototypes/_Goobstation/NTR/bsd.yml
  Resources/Prototypes/_Goobstation/NTR/droppod.yml
  Resources/Prototypes/_Goobstation/NTR/task_specific.yml
  Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
  Resources/Prototypes/_Goobstation/tags.yml
  Resources/Textures/_Goobstation/Objects/Specific/DropPod/landingpod.rsi/landing.png
  Resources/Textures/_Goobstation/Objects/Specific/DropPod/landingpod.rsi/meta.json
  Resources/Textures/_Goobstation/Objects/Specific/DropPod/marker.rsi/marker.png
  Resources/Textures/_Goobstation/Objects/Specific/DropPod/marker.rsi/marker_ping.png
  Resources/Textures/_Goobstation/Objects/Specific/DropPod/marker.rsi/meta.json
  Resources/Textures/_Goobstation/Objects/Specific/DropPod/supplypod.rsi/landed-opened.png
  Resources/Textures/_Goobstation/Objects/Specific/DropPod/supplypod.rsi/landed.png
  Resources/Textures/_Goobstation/Objects/Specific/DropPod/supplypod.rsi/meta.json
Labels: S: Untriaged, size/L

#13 cleanup
  Content.Goobstation.Client/NTR/UI/NtrTaskBoundUserInterface.cs
  Content.Goobstation.Client/NTR/UI/NtrTaskMenu.xaml.cs
  Content.Goobstation.Client/NTR/UI/TaskEntry.xaml.cs
  Content.Goobstation.Server/Administration/AddStoreTimeCommand.cs
  Content.Goobstation.Server/NTR/CorporateOverrideSystem.cs
  Content.Goobstation.Server/NTR/Documents/RandomDocumentSystem.cs
  Content.Goobstation.Server/NTR/Documents/SpamDocumentSystem.cs
  Content.Goobstation.Server/NTR/Events/LateJobUnlockRule.cs
  Content.Goobstation.Server/NTR/NTRTaskSystem.cs
  Content.Goobstation.Server/NTR/Scan/BriefcaseScannerSystem.cs
  Content.Goobstation.Shared/NTR/Documents/RandomDocumentComponent.cs
  Content.Goobstation.Shared/NTR/Events/NtrListingPurchaseEvent.cs
  Content.Goobstation.Shared/NTR/Events/TaskCompletedEvent.cs
  Content.Goobstation.Shared/NTR/Events/TaskFailedEvent.cs
  Content.Goobstation.Shared/NTR/NtrBankAccountComponent.cs
  Content.Goobstation.Shared/NTR/NtrTaskConsoleComponent.cs
  Content.Goobstation.Shared/NTR/NtrTaskData.cs
  Content.Goobstation.Shared/NTR/NtrTaskDatabaseComponent.cs
  Content.Goobstation.Shared/NTR/NtrTaskHistoryData.cs
  Content.Goobstation.Shared/NTR/NtrTaskPrototype.cs
  Content.Goobstation.Shared/NTR/Scan/BriefcaseScannerDoAfterEvent.cs
Labels: Changes: UI
